language: php 
php: 
 - 5.3

env:
 - DB=MYSQL CORE_RELEASE=3.0
 - DB=PGSQL CORE_RELEASE=3.0

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.0

before_script:
 - phpenv rehash
 - ./tests/travis/travis_setup.php --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit cms/tests/

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - 2.4
    - post-2.4
    - translation-staging

notifications:
  irc:
    channels:
     - "irc.freenode.org#silverstripe"
