mappings:
  CMSBatchAction_Publish: SilverStripe\CMS\BatchActions\CMSBatchAction_Publish
  CMSBatchAction_Unpublish: SilverStripe\CMS\BatchActions\CMSBatchAction_Unpublish
  CMSBatchAction_Archive: SilverStripe\CMS\BatchActions\CMSBatchAction_Archive
  CMSBatchAction_Restore: SilverStripe\CMS\BatchActions\CMSBatchAction_Restore
  CMSMain: SilverStripe\CMS\Controllers\CMSMain
  CMSPageAddController: SilverStripe\CMS\Controllers\CMSPageAddController
  CMSPageEditController: SilverStripe\CMS\Controllers\CMSPageEditController
  CMSPageHistoryController: SilverStripe\CMS\Controllers\CMSPageHistoryController
  CMSPagesController: SilverStripe\CMS\Controllers\CMSPagesController
  CMSPageSettingsController: SilverStripe\CMS\Controllers\CMSPageSettingsController
  CMSSiteTreeFilter: SilverStripe\CMS\Controllers\CMSSiteTreeFilter
  CMSSiteTreeFilter_PublishedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_PublishedPages
  CMSSiteTreeFilter_DeletedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_DeletedPages
  CMSSiteTreeFilter_ChangedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_ChangedPages
  CMSSiteTreeFilter_StatusRemovedFromDraftPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusRemovedFromDraftPages
  CMSSiteTreeFilter_StatusDraftPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusDraftPages
  CMSSiteTreeFilter_StatusDeletedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusDeletedPages
  CMSSiteTreeFilter_Search: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_Search
  ContentController: SilverStripe\CMS\Controllers\ContentController
  ErrorPageControllerExtension: SilverStripe\ErrorPage\ErrorPageControllerExtension
  ErrorPageFileExtension: SilverStripe\ErrorPage\ErrorPageFileExtension
  LeftAndMainPageIconsExtension: SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
  ModelAsController: SilverStripe\CMS\Controllers\ModelAsController
  OldPageRedirector: SilverStripe\CMS\Controllers\OldPageRedirector
  RootURLController: SilverStripe\CMS\Controllers\RootURLController
  SilverStripeNavigator: SilverStripe\CMS\Controllers\SilverStripeNavigator
  SilverStripeNavigatorItem: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem
  SilverStripeNavigatorItem_CMSLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_CMSLink
  SilverStripeNavigatorItem_StageLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_StageLink
  SilverStripeNavigatorItem_LiveLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_LiveLink
  SilverStripeNavigatorItem_ArchiveLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_ArchiveLink
  SiteTreeURLSegmentField: SilverStripe\CMS\Forms\SiteTreeURLSegmentField
  SiteTreeURLSegmentField_Readonly: SilverStripe\CMS\Forms\SiteTreeURLSegmentField_Readonly
  CurrentPageIdentifier: SilverStripe\CMS\Model\CurrentPageIdentifier
  ErrorPage: SilverStripe\ErrorPage\ErrorPage
  ErrorPage_Controller: SilverStripe\ErrorPage\ErrorPageController
  RedirectorPage: SilverStripe\CMS\Model\RedirectorPage
  RedirectorPage_Controller: SilverStripe\CMS\Model\RedirectorPageController
  SiteTree: SilverStripe\CMS\Model\SiteTree
  SiteTreeExtension: SilverStripe\CMS\Model\SiteTreeExtension
  SiteTreeFileExtension: SilverStripe\CMS\Model\SiteTreeFileExtension
  SiteTreeFolderExtension: SilverStripe\CMS\Model\SiteTreeFolderExtension
  SiteTreeLinkTracking: SilverStripe\CMS\Model\SiteTreeLinkTracking
  SiteTreeLinkTracking_Parser: SilverStripe\CMS\Model\SiteTreeLinkTracking_Parser
  VirtualPage: SilverStripe\CMS\Model\VirtualPage
  BrokenFilesReport: SilverStripe\CMS\Reports\BrokenFilesReport
  SideReport_BrokenFiles: SilverStripe\CMS\Reports\BrokenFilesReport
  BrokenLinksReport: SilverStripe\CMS\Reports\BrokenLinksReport
  SideReport_BrokenLinks: SilverStripe\CMS\Reports\BrokenLinksReport
  BrokenRedirectorPagesReport: SilverStripe\CMS\Reports\BrokenRedirectorPagesReport
  SideReport_BrokenRedirectorPages: SilverStripe\CMS\Reports\BrokenRedirectorPagesReport
  BrokenVirtualPagesReport: SilverStripe\CMS\Reports\BrokenVirtualPagesReport
  SideReport_BrokenVirtualPages: SilverStripe\CMS\Reports\BrokenVirtualPagesReport
  EmptyPagesReport: SilverStripe\CMS\Reports\EmptyPagesReport
  SideReport_EmptyPages: SilverStripe\CMS\Reports\EmptyPagesReport
  RecentlyEditedReport: SilverStripe\CMS\Reports\RecentlyEditedReport
  SideReport_RecentlyEdited: SilverStripe\CMS\Reports\RecentlyEditedReport
  ContentControllerSearchExtension: SilverStripe\CMS\Search\ContentControllerSearchExtension
  SearchForm: SilverStripe\CMS\Search\SearchForm
  MigrateSiteTreeLinkingTask: SilverStripe\CMS\Tasks\MigrateSiteTreeLinkingTask
  RemoveOrphanedPagesTask: SilverStripe\CMS\Tasks\RemoveOrphanedPagesTask
  SiteTreeMaintenanceTask: SilverStripe\CMS\Tasks\SiteTreeMaintenanceTask
  AssetAdmin: SilverStripe\AssetAdmin\Controller\AssetAdmin
  AssetTableField: SilverStripe\AssetAdmin\Controller\AssetAdmin
  CMSAddPageController: SilverStripe\CMS\Controllers\CMSPageAddController
  CMSBatchActions: SilverStripe\Admin\CMSBatchAction
  CMSSearch: SilverStripe\CMS\Search\SearchForm
  ContentControl: SilverStripe\CMS\Controllers\ContentController
  Permissions: SilverStripe\Security\Permission
  SITETREE: SilverStripe\CMS\Model\SiteTree
  CMSMain_left_ss: SilverStripe\CMS\Controllers\CMSMain
  CMSPageHistoryController_versions_ss: SilverStripe\CMS\Controllers\CMSPageHistoryController
  CMSPagesController_ContentToolbar_ss: SilverStripe\CMS\Controllers\CMSPageHistoryController
  CMSSIteTreeFilter_PublishedPages: SilverStripe\CMS\Controllers\CMSSIteTreeFilter_PublishedPages
  URLSegmentField: SilverStripe\CMS\Forms\SiteTreeURLSegmentField
  CMSPagesController_Tools_ss: SilverStripe\CMS\Controllers\CMSPagesController
  LeftAndMain: SilverStripe\Admin\LeftAndMain
