---
Name: cmsextensions
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\CMS\Model\SiteTreeFileExtension
---
Name: cmsmodals
---
SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\CMS\Forms\InternalLinkModalExtension
---
Name: cmshierarchy
---
SilverStripe\ORM\Hierarchy\Hierarchy:
  node_threshold_total: 50
  node_threshold_leaf: 250