LeftAndMain:
  extensions:
    - LeftAndMainPageIconsExtension
Controller:
  extensions:
    - ErrorPageControllerExtension
Form:
  extensions:
    - ErrorPageControllerExtension
File:
  extensions:
    - ErrorPageFileExtension
