---
Name: cmsextensions
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\CMS\Model\SiteTreeFileExtension
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - SilverStripe\CMS\Model\SiteTreeFileFormFactoryExtension
---
Name: cmsmodals
---
SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\CMS\Forms\InternalLinkModalExtension
