SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
Controller:
  extensions:
    - SilverStripe\CMS\Controllers\ErrorPageControllerExtension
Form:
  extensions:
    - SilverStripe\CMS\Controllers\ErrorPageControllerExtension
File:
  extensions:
    - SilverStripe\CMS\Controllers\ErrorPageFileExtension
