---
Name: modelascontrollerroutes
Before: '*'
After: '#rootroutes'
---
Director:
  rules:
    '': 'SilverStripe\CMS\Controllers\RootURLController'
    'RemoveOrphanedPagesTask//$Action/$ID/$OtherID': 'SilverStripe\CMS\Tasks\RemoveOrphanedPagesTask'
    'SiteTreeMaintenanceTask//$Action/$ID/$OtherID': 'SilverStripe\CMS\Tasks\SiteTreeMaintenanceTask'
    '$URLSegment//$Action/$ID/$OtherID': 'SilverStripe\CMS\Controllers\ModelAsController'
---
Name: legacycmsroutes
After: '#adminroutes'
---
Director:
  rules:
    'admin/cms': '->admin/pages'
