---
Name: modelascontrollerroutes
Before: '*'
After: '#rootroutes'
---
Director:
  rules:
    '': 'RootURLController'
    'RemoveOrphanedPagesTask//$Action/$ID/$OtherID': 'RemoveOrphanedPagesTask'
    'SiteTreeMaintenanceTask//$Action/$ID/$OtherID': 'SiteTreeMaintenanceTask'
    '$URLSegment//$Action/$ID/$OtherID': 'ModelAsController'
---
Name: legacycmsroutes
After: '#adminroutes'
---
Director:
  rules:
    'admin/cms': '->admin/pages'
